name: Build and Deploy
on:
    workflow_dispatch:

jobs:
    web:
        name: Build and Deploy
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 19

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: 8.6.9

            - name: Build
              run: |
                  git apply patches/github-pages.patch
                  pnpm install
                  pnpm diagrams:build
                  pnpm blog:build || true

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./packages/blog/dist
